### ISSUE TITLE
Hi ~

### ISSUE THREAD

**Issue by Kguru99** [yyvess/gconf#2]
gconf looks like very useful, i want to apply gconf in my project...
but, now my coding level is low....
i need another example like java main app.. not test case..
would you please make another example for me ?

**Comment by yyvess** [comment]
Hi,
I have added a sample [MyApp](https://github.com/yyvess/gconf/blob/master/src/test/java/net/jmob/guice/conf/core/samples/simple/MyApp.java) with a main() method.

Regards,

Yves

**Comment by Kguru99** [comment]
:+1:
