### ISSUE TITLE
Thank you Yvess!  but i have another problem...

### ISSUE THREAD

**Issue by Kguru99** [yyvess/gconf#3]
Previous answer Thank you very much :dancer: .

gconf can read only resources directory.... but I want to read a file on the outside.
because...
If the files in the project, config is dependent on the project.
If config is modified, the need to re-build the project...
i don't want it....
I hope config is reapplied By restarting the application.
Is there another way?

**Comment by yyvess** [comment]
Welcome on Java world !
You are right, this lib can read file only on the classpath. But in additionally as you jar, you can add an external directory on your classpath where your external configuration is stored.
Please read : http://stackoverflow.com/questions/2232602/java-jar-access-external-configuration-file

**Comment by Kguru99** [comment]
:+1:
