### ISSUE TITLE
Use of variable substitution

### ISSUE THREAD

**Issue by dany-eudes** [yyvess/gconf#4]
Is it possible?

See  this case:

```
myconfig {
  var1 {
    value = "Hello"
  }
  var2 {
    value = ${myconfig.var1.value}", World!"
  }
}

```

This isn't working for me.

> Exception in thread "main" com.google.inject.CreationException: Guice creation errors:
> 
> 1) Error notifying TypeListener net.jmob.guice.conf.core.impl.ConfigurationListener@40ef3420 (bound at net.jmob.guice.conf.core.ConfigurationModule.configure(ConfigurationModule.java:34)) of com.celerasoft.qadmin.services.impl.ConfigService.
>  Reason: com.typesafe.config.ConfigException$NotResolved: called valueType() on value with unresolved substitutions, need to Config#resolve() first, see API docs

**Comment by yyvess** [comment]
Actually not.

Constructor or teh class _net.jmob.guice.conf.core.impl.injector.InjectorBuilder_ must be patched to do that.

`
    public InjectorBuilder(Class beanClass) {
        this.beanClass = beanClass;
        if (getAnnotationPath().isEmpty()) {
            this.config  = parseResourcesAnySyntax(getAnnotationValue(), getOptions())
                .resolve();
        } else {
            this.config  = parseResourcesAnySyntax(getAnnotationValue(), getOptions())
                .getConfig(getAnnotationPath())
                .resolve();
        }
    }
`

**Comment by yyvess** [comment]
Feature push on master  [See sample usage]( https://github.com/yyvess/gconf/blob/master/src/test/java/net/jmob/guice/conf/core/samples/advenced/ResolvedConfig.java)

**Comment by yyvess** [comment]
Supported from 1.3.0.
See the sample ResolvedConfig
https://github.com/yyvess/gconf/blob/master/src/test/java/net/jmob/guice/conf/core/samples/advenced/ResolvedConfig.java
