### ISSUE TITLE
Substitutions are not resolved

### ISSUE THREAD

**Issue by ecausarano** [yyvess/gconf#9]
When using parametrized configuration values will throw exception:

Caused by: com.typesafe.config.ConfigException$NotResolved: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${TEST_PARM})

Adding call is trivial but it breaks a test because resolution returns a new configuration object (discarding the mock the test depends on.) Perhaps you have a better idea to fix this (or the test)?

**Comment by yyvess** [comment]
Hi,
Do you have try to use the option resolve = true ?

@BindConfig(value = "net/jmob/guice/conf/core/samples/resolved", resolve = true)

**Comment by ecausarano** [comment]
Hi Yyves,

nope I didn't, thanks for pointing it out. Can you mention it in the README, or make the default value true?

**Comment by yyvess** [comment]
Hi !
As discuss by email, 
you are welcome to create a PR to improve Readme 😉
Yves
